# Generated by scripts/update-tap-formula.sh on each release. Do not edit
# in the tap repo.
#
# This is a formula, not a cask, on purpose: Homebrew quarantines cask
# downloads, and Gatekeeper kills quarantined binaries that are not
# notarized. Formula downloads are not quarantined.
class KubectlMole < Formula
  desc "Watch Kubernetes workloads until they settle, then explain what broke"
  homepage "https://github.com/justin-tahara/kubectl-mole"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_darwin_arm64.tar.gz"
      sha256 "8486506f4437bcbfca9c4006c65c86218f2748f90b6006dc1737aab82dfdec4b"
    else
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_darwin_amd64.tar.gz"
      sha256 "3fa7216b878f90456836cf5ad3834da4cd1f08ee8f46d3c511c2567630ac818d"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_linux_arm64.tar.gz"
      sha256 "8ad4f2f39c7f2a55f10e769b0534da10aff254569b06d5638dbfadcca5b18581"
    else
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_linux_amd64.tar.gz"
      sha256 "91bb2d3591ed176036f40975cb4c40c054ac98bc0eb5a43514a1201073630d51"
    end
  end

  def install
    bin.install "kubectl-mole"
  end

  def caveats
    <<~EOS
      kubectl-mole needs read access to workloads, pods, and events.
      A minimal ClusterRole ships with the repo: deploy/rbac.yaml
    EOS
  end

  test do
    assert_match "kubectl-mole version v#{version}", shell_output("#{bin}/kubectl-mole --version")
  end
end
