# Generated by scripts/update-tap-formula.sh on each release. Do not edit
# in the tap repo.
#
# This is a formula, not a cask, on purpose: Homebrew quarantines cask
# downloads, and Gatekeeper kills quarantined binaries that are not
# notarized. Formula downloads are not quarantined.
class KubectlMole < Formula
  desc "Watch Kubernetes workloads until they settle, then explain what broke"
  homepage "https://github.com/justin-tahara/kubectl-mole"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_darwin_arm64.tar.gz"
      sha256 "9f88dd1cfa211099100b13e32942f688e0147103c5bf6256c514ba408b392bf7"
    else
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_darwin_amd64.tar.gz"
      sha256 "99fc7b075fe0a08b2e64c8b44bac2c48b6a3c3f5ce63f8397ec1b987d2bfcdeb"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_linux_arm64.tar.gz"
      sha256 "5efea9a070a4868e90534e7eadd48fc313ca9f3128860b0ec0663989e6ba45d5"
    else
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_linux_amd64.tar.gz"
      sha256 "f2c8210bbe1c74820bb2914e5cef157ebd273410c614ef4d2b9c19e426e7b294"
    end
  end

  def install
    bin.install "kubectl-mole"
  end

  def caveats
    <<~EOS
      kubectl-mole needs read access to workloads, pods, and events.
      A minimal ClusterRole ships with the repo: deploy/rbac.yaml
    EOS
  end

  test do
    assert_match "kubectl-mole version v#{version}", shell_output("#{bin}/kubectl-mole --version")
  end
end
