# Generated by scripts/update-tap-formula.sh on each release. Do not edit
# in the tap repo.
#
# This is a formula, not a cask, on purpose: Homebrew quarantines cask
# downloads, and Gatekeeper kills quarantined binaries that are not
# notarized. Formula downloads are not quarantined.
class KubectlMole < Formula
  desc "Watch Kubernetes workloads until they settle, then explain what broke"
  homepage "https://github.com/justin-tahara/kubectl-mole"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_darwin_arm64.tar.gz"
      sha256 "e4bb87b5d2960cebd2eb30bad9239946bacdb5f25bce60eb7937098994ea1741"
    else
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_darwin_amd64.tar.gz"
      sha256 "1e45a8cc87e049bcdaa4e50c4790153207c2d729f4627ac137b722f0e78e1b2c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_linux_arm64.tar.gz"
      sha256 "ed9914014ef7c2ec37cf70a64de79f3dd7e6def734886f1773eb9ecd44a9ca8b"
    else
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_linux_amd64.tar.gz"
      sha256 "888266bf04d0b782e2a02e27bbf03f1244987962906ac5e1a5c6f16ebb2a4c29"
    end
  end

  def install
    bin.install "kubectl-mole"
  end

  def caveats
    <<~EOS
      kubectl-mole needs read access to workloads, pods, and events.
      A minimal ClusterRole ships with the repo: deploy/rbac.yaml
    EOS
  end

  test do
    assert_match "kubectl-mole version v#{version}", shell_output("#{bin}/kubectl-mole --version")
  end
end
